ALTER TABLE "organisations"
ADD COLUMN IF NOT EXISTS "standardClockInTime" TEXT DEFAULT '08:00',
ADD COLUMN IF NOT EXISTS "standardClockOutTime" TEXT DEFAULT '17:00',
ADD COLUMN IF NOT EXISTS "lateClockInThresholdMinutes" INTEGER DEFAULT 15,
ADD COLUMN IF NOT EXISTS "defaultWorkingHoursPerDay" INTEGER DEFAULT 8,
ADD COLUMN IF NOT EXISTS "leaveYearStartMonth" INTEGER DEFAULT 1,
ADD COLUMN IF NOT EXISTS "defaultAnnualLeaveDays" INTEGER DEFAULT 15,
ADD COLUMN IF NOT EXISTS "sickLeaveCycleDays" INTEGER DEFAULT 30,
ADD COLUMN IF NOT EXISTS "sickLeaveDocumentThresholdDays" INTEGER DEFAULT 2,
ADD COLUMN IF NOT EXISTS "autoMarkMissedClockOut" BOOLEAN DEFAULT true;